export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const GET_ALL_DOCTYPES = "GET_ALL_DOCTYPES";
export const ADD_DOCTYPE = "ADD_DOC_TYPE";
export const UPDATE_DOCTYPE = "UPDATE_DOCTYPE";
export const DELETE_DOCTYPE = "DELETE_DOCTYPE";

export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_FIELDS = "GET_ALL_FIELDS";
export const ADD_FIELD = "ADD_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";

export const GET_ALL_DOCTYPEFIELDS = "GET_ALL_DOCTYPEFIELDS";
export const ADD_DOCTYPEFIELD = "ADD_DOCTYPEFIELD";
export const UPDATE_DOCTYPEFIELD = "UPDATE_DOCTYPEFIELD";
export const DELETE_DOCTYPEFIELD = "DELETE_DOCTYPEFIELD";
