export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const GET_ALL_DOCTYPES = "GET_ALL_DOCTYPES";
export const ADD_DOCTYPE = "ADD_DOC_TYPE";
export const UPDATE_DOCTYPE = "UPDATE_DOCTYPE";
export const DELETE_DOCTYPE = "DELETE_DOCTYPE";

export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER = "LOGIN_USER";
