export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const GET_FILTERED_DEPARTMENTS = "GET_FILTERED_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const GET_ALL_DOCTYPES = "GET_ALL_DOCTYPES";
export const GET_FILTERED_DOCTYPES = "GET_FILTERED_DOCTYPES";
export const ADD_DOCTYPE = "ADD_DOC_TYPE";
export const UPDATE_DOCTYPE = "UPDATE_DOCTYPE";
export const DELETE_DOCTYPE = "DELETE_DOCTYPE";

export const REGISTER_USER = "REGISTER_USER";
export const SEND_RESET_MAIL = "SEND_RESET_MAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SEND_VERIFICATION_LINK = "SEND_VERIFICATION_LINK";
export const VERIFY_EMAIL = "VERIFY_EMAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_FILTERED_USERS = "GET_FILTERED_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_CLEARANCE = "CHANGE_CLEARANCE";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_FIELDS = "GET_ALL_FIELDS";
export const GET_FILTERED_FIELDS = "GET_FILTERED_FIELDS";
export const ADD_FIELD = "ADD_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";

export const GET_ALL_DOCTYPEFIELDS = "GET_ALL_DOCTYPEFIELDS";
export const GET_FILTERED_DOCTYPEFIELDS = "GET_FILTERED_DOCTYPEFIELDS";
export const ADD_DOCTYPEFIELD = "ADD_DOCTYPEFIELD";
export const UPDATE_DOCTYPEFIELD = "UPDATE_DOCTYPEFIELD";
export const DELETE_DOCTYPEFIELD = "DELETE_DOCTYPEFIELD";

export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const GET_ALL_DOCUMENTS = "GET_ALL_DOCUMENTS";
export const GET_PREVIEW = "GET_PREVIEW";
export const GET_USER_DOCUMENTS = "GET_USER_DOCUMENTS";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const GET_DOCUMENTS_BY_TAG = "GET_DOCUMENTS_BY_TAG"; //filter by selected custom tag of the user

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const SEND_NOTIFICATION = "SEND_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const ADD_COMMENT = "ADD_COMMENT";
export const GET_COMMENT_BY_DOC = "GET_COMMENT_BY_DOC";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const ADD_TAG = "ADD_TAG";
export const GET_TAGS_BY_USER = "GET_TAGS_BY_USER";
export const GET_TAGS_BY_DOC = "GET_TAGS_BY_DOC";
export const DELETE_TAG = "DELETE_TAG";

export const GET_ALL_TAG_NAMES = "GET_ALL_TAG_NAMES";
export const ADD_TAG_NAME = "ADD_TAG_NAME";

export const GET_ALL_INDEXERS = "GET_ALL_INDEXERS";
export const ADD_INDEXER = "ADD_INDEXER";
export const UPDATE_INDEXER = "UPDATE_INDEXER";
